[build]
  publish = "public/"
  command = "hugo"
[build.environment]
  HUGO_VERSION = "0.62.0"
[context.production]
  branch = "master"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  prettify_urls = true
[build.processing.images]
  compress = true


[Settings]
  ID = "ees3310"

[[redirects]]
  from = "https://www.ees3310.jgilligan.org/*"
  to   = "https://ees3310.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://www.ees3310.jgilligan.org/*"
  to   = "https://ees3310.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://ees3310.netlify.com/*"
  to   = "https://ees3310.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://ees3310.netlify.com/*"
  to   = "https://ees3310.jgilligan.org/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/static/*"
  to = "https://static.jgilligan.org/ees3310/:splat"
  status = 200

[[redirects]]
  from = "/climatemodels/*"
  to = "https://climatemodels.jgilligan.org/:splat"
  status = 302

[[redirects]]
  from = "/decarbonization/*"
  to = "https://shiny.jgilligan.org/ees-3310/kaya-tool/:splat"
  status = 302

[[redirects]]
  from = "/emissions_trading/*"
  to = "https://shiny.jgilligan.org/ees-3310/emissions_trading/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
