---
title: Many variables (part 2)
class_date: '2022-09-15'
class_number: 7
weight: 7
slug: reading_07
pubdate: '2022-07-31'
date: '2022-09-15'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_07.pdf
---
## Reading:

### Required Reading (everyone):

* Statistical Rethinking, Ch. 5 ("The Many Variables and The Superfluous Waffles"), sections 5.2-5.4, pp. 144--158.

### Reading Notes:

We pick up where the last assignment left off: We look at _masked relationships_ in which multiple predictor variables influence the dependent outcome variable, but you can't see the relationship when you look at pairwise relations between either of the predictors and the outcome. This can happen when two predictors are correlated with each other, and they have opposite causal influences on the outcome variable. The book shows how to use plots, models, and DAGs to understand _masked relationships_.

We also start to look at categorical variables that don't correspond to numbers. Examples of these include sex, developmental status (infant, juvenile, adult), geographic region (North America, South America, Africa, Europe, etc.), and so forth.

By the end of the chapter, you should have a sense of how to analyze complicated relationships among multiple variables, including different kinds of variables.
